Improve error handling
mosaicdao/faucet pull request #14
Opened 2019-04-11 14:42 UTC by schemar

Error handling of the faucet is improved considerably. In my local
tests, the process never crashed and there were no more warnings of
uncaught exceptions.

When the websocket connection of web3 breaks, the server immediately
returns an error to the client, but stays active. As soon as web3/the
websocket can reconnect to the node, the faucet is functional again.

I updated the error messaging in a way where the faucet would always log
details of the error, but it would not always return error details to
the client to not leak any potentially sensitive information to random
clients.

I updated the Logger to no longer handle 'uncaughtEvents', as that
interfered with the correct error handling.

I had to update the Web3js version (to `beta.52`) in the faucet, as the
old version we usually use (`beta.37`) doesn't do error handling correct.
It 'throws' in an event emitter and that cannot be caught.

With the updated Web3js it was no longer possible to use the
`ZeroClientProvider` together with the `Accounts` how we used to.
Furthermore, the latest beta automatically signs transactions locally,
if the `from` address is unlocked in `eth.accounts.wallet`.
So I removed the `ZeroClientProvider` and switched to the Web3js wallet
for accounts and signing.

The problem now is that Web3js doesn't do proper nonce handling. Thus,
I  added a very simple nonce handler to get started (`n + 1`). It
fetches the current nonce from the node only when it starts.

It also doesn't do gas estimation, so that needs to be done separately
now before sending a transaction.

There was also an issue that I cannot do gas estimation asynchronously
while still being able to access the `PromiEvent`'s events. When waiting
for a promise to resolve, it would also resolve the wrapped PromiEvent.
As a fix, I wrapped the `fill` responses in Promises which resolve (or
reject) upon the transaction hash (or error) event of the underlying
transaction. This way, we can do async/await calls to get the nonce or
the estimated gas of a transaction.

Also:

* I moved the ABI into a TypeScript class.
* Added static typing wherever I found it was missing.
* Generally refactored the code to be more in-line with best practices.

Fixes #9

2019-04-12 13:59 UTC, 0xsarvesh requested changes
Nice work 🙌 
Some feedback inline.

2019-04-12 13:59 UTC, 0xsarvesh commented on src/ABI.ts
> +export default class ABI {
I think we should start using npm package to get abi and bin for ERC20 contract. 
For instance https://www.npmjs.com/package/openzeppelin-solidity

```
const { abi } = require('openzeppelin-solidity/build/contracts/ERC20')

```

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/CoinFaucet.ts
> +  public fill(address: string): Promise<string> {
If I understood it correctly, this function will return `Promise<void>` not Promise<string> because of `Logger.info` statement.

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/CoinFaucet.ts
> +    transaction.gas = await this.account.web3.eth.estimateGas(transaction);
gas can also be cached in the memory, I think.

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/CoinFaucet.ts
> +    // Wrapping the event emitter in a promise to resolve or reject immediately when the events are
👍

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/EIP20Faucet.ts
> +    await transferTx.call({ from: this.account.address });
I think, estimate gas will also fail if the `call` fails.  Maybe call is not required here always. 🤔

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/EIP20Faucet.ts
> +    const gas = await transferTx.estimateGas({ from: this.account.address });
This gas can be cached in memory. 
Also, base coin transfer and ERC20 transfer gas are constant theoretically. It can be even taken as config.

2019-04-12 13:59 UTC, 0xsarvesh commented on src/Faucet/Faucet.ts
> +  account: Account;
Maybe another field for transaction gas estimation value.

2019-04-15 15:26 UTC, schemar commented on src/ABI.ts
> +export default class ABI {
Ah great! I didn't know the package included built contracts' stuff. Will add!

2019-04-15 15:35 UTC, schemar commented on src/ABI.ts
> +export default class ABI {
Done, but did require a small nastiness...

2019-04-15 15:38 UTC, schemar commented on src/Faucet/CoinFaucet.ts
> +  public fill(address: string): Promise<string> {
It returns `Promise<string>`, as it returns the `transactionHashPromise` and not the return value of `transactionHashPromise.then()`.

The return value *would* be the return value of `Logger.info`: `Logger` (winston logger) if the method would return the return value of `.then()`.

2019-04-15 15:55 UTC, schemar commented on src/Faucet/EIP20Faucet.ts
> +    await transferTx.call({ from: this.account.address });
Updated 👍

2019-04-15 15:56 UTC, schemar commented
@sarvesh-ost updated and ready for review again. I also caught a small uncaught promise rejection in the CoinFaucet that is now caught.

I would say we keep the gas estimation as it is "free" and makes the faucet very robust. No need to optimize prematurely. What do you think @sarvesh-ost ?

2019-04-15 15:57 UTC, schemar commented
Please note the dirty (required) type juggling in order to be able to use openzeppelin (in `ABI.ts`)

2019-04-22 05:49 UTC, 0xsarvesh approved these changes
LGTM 👍  

I feel gas estimation should be cached if we want to scale the faucet for future use. Interaction with geth for estimating gas is slow which makes overall faucet slow. ETH transfer (21000 gas) and the ERC20 transfer takes constant gas. 

Maybe this is future work and out of the scope of this PR 👍

2019-04-22 05:51 UTC, merged